### ISSUE TITLE
SpanishStemmer raises IndexError: string index out of range

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#493]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/493) by Stephane Boisson (Bitbucket: [sboisson](https://bitbucket.org/sboisson), GitHub: [sboisson](https://github.com/sboisson)).**

----------------------------------------

Some words cause an exception.

Not sure if issues is in [original algorithm](http://snowball.tartarus.org/algorithms/spanish/stemmer.html) or in python implementation.

Example reproducing the issue using Whoosh 2.7.4:

```
#!python
# -*- coding: utf-8 -*-
from whoosh.lang.snowball.spanish import SpanishStemmer

stemmer = SpanishStemmer()
print stemmer.stem(u"B\xe8gue")

```

Results:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sboisson/Documents/venv/lib/python2.7/site-packages/whoosh/lang/snowball/spanish.py", line 239, in stem
    if len(word) >= 2 and word[-2:] == "gu" and rv[-1] == "u":
IndexError: string index out of range
```

**Comment by fortable1999** [comment]
I merged it:
https://github.com/whoosh-community/whoosh/pull/498
